%%{init: {
    "themeVariables": {"fontSize": "24px"}, 
    "sequence": {"boxMargin": 20}
}}%%
sequenceDiagram
autonumber
participant A as User Agent
participant B as DV / LC
participant C as RD&lt;br/&gt;front-channel-channel
participant D as RD&lt;br/&gt;back-channel-channel
participant E as AD
A->>B: local logout
B-->>A: LogoutRequest
A->>C: LogoutRequest
rect rgba(75, 75, 75,.4)
    Note over D,E:  Out of Scope: see RD#8594;AD/BVD
    C->>E: 
    E->>E: 
    E-->>C: 
end 
rect rgba(255,0,0,.1)
rect rgba(255,0,0,.1)
    C-->>A: LogoutResponse
    A->>B: LogoutResponse
end
end
