name: Build and Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
jobs:
  build-index:
    name: Build index.html
    uses: Logius-standaarden/Automatisering/.github/workflows/build.yml@pr-timvdlippe-meerdere-documenten
    with:
      multiple_files: true
  build-index-dv:
    name: Build index-dv.html
    uses: Logius-standaarden/Automatisering/.github/workflows/build.yml@pr-timvdlippe-meerdere-documenten
    with:
      source_input_file_name: 'index_dv.html'
      multiple_files: true
  build:
    needs: [ build-index, build-index-dv ]
    name: Update cache
    runs-on: ubuntu-22.04
    steps:
      - name: Restore cache for `index.html`
        uses: actions/cache/restore@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}-index.html
      - name: Restore cache for `index_dv.html`
        uses: actions/cache/restore@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}-index_dv.html
      - name: Welke bestanden zijn er
        run: ls ~/static
      - name: Save cache for both
        uses: actions/cache/save@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}

  check:
    needs: build
    name: Check
    uses: Logius-standaarden/Automatisering/.github/workflows/check.yml@pr-timvdlippe-meerdere-documenten
  publish:
    needs: build
    name: Publish (Logius)
    uses: Logius-standaarden/Automatisering/.github/workflows/publish.yml@pr-timvdlippe-meerdere-documenten
    secrets: inherit
